name: Build EPUB from Markdown
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pandoc
        run: sudo apt update && sudo apt install -y pandoc
      - name: Convert Markdown to EPUB
        run: |
          mkdir -p dist
          pandoc \
            $(find src/frontend -name "*.md" | sort) \
            --metadata-file=metadata.yml \
            --epub-cover-image="src/assets/icon.png" \
            --epub-embed-font="src/assets/SourceHanSansCN-Regular.otf" \
            --standalone \
            -o dist/前端面试题库.epub
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-inter-view-epub
          path: dist/前端面试题库.epub
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download built EPUB
        uses: actions/download-artifact@v4
        with:
          name: frontend-inter-view-epub
          path: dist
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload to GitHub Packages
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/前端面试题库.epub
          asset_name: frontend-interview.epub
          asset_content_type: application/epub+zip
